### PR TITLE
Fix all the things

### LINKED ISSUE #2: Readme `npx` doesn't actually work yet
I opted for: `npx https://github.com/mozilla/properties-to-ftl`.

Feel free to close if this is intended, but I'm "kicking the tires" on the migration script.

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/properties-to-ftl - Not found
npm ERR! 404
npm ERR! 404  'properties-to-ftl@latest' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

### LINKED ISSUE #3: Confusing output for the `list` command
```
➤  properties-to-ftl list devtools/client/locales/en-US/toolbox.properties
devtools/client/locales/en-US/toolbox.properties [ 52, 5, 7, 2 ]
```

I'm not really sure what the numbers mean here.

### LINKED ISSUE #4: No mention of --ftl-path and --ftl-prefix in help message
```
Error: No migrations defined!

In order to migrate strings to Fluent, the .properties file must include
FTL metadata comments:

# FTL path: foo/bar/baz.ftl
# FTL prefix: foobar

For more information, see: https://github.com/mozilla/properties-to-ftl#readme
```

I would prefer to only interact with the CLI, and not add the FTL metadata comments when migrating a single .properties file. It would be nice if the help message mentioned these.

Also, when listing the docs URL, it would be nice if it would jump directly to a section heading dealing with the specific issue.

### LINKED ISSUE #7: Script crashes if Black is not installed
I know if you follow the directions on the README it tells you to install Black. However, I did not do this and got a confusing error message. It would be nice if the script detected the presence of Black. Also, I prefer running `./mach lint --fix path/to/python.py` when working in python in mozilla-central. It may be more appropriate to invoke the `mach` machinery which should be able to properly install and run the linters.

### LINKED ISSUE #8: Consider Including a full copy/pasteable command that "just works™"
It would be nice if I could copy and paste a command with a path to a .properties file, and a path to a .ftl file, and have it "just work™" by updating the paths. This would lower the user friction to trying it out first. I found the first reference to a `.jsm` file to be confusing as I was working in a DevTools context using fluent-react, so the JSM changes were not appropriate in my case

### PR DESCRIPTION
**Pull request by eemeli**
Fixes #3 by adding a separate `--var-counts` CLI argument for the `properties-to-ftl list` command.

Fixes #4 by adding a clearer mention of the required `--ftl-path` argument.

Fixes #7 by switching to defaulting to `./mach lint --fix` as the lint command.

Fixes #8 by expanding the README with a non-JS properties migration tutorial.

Once merged, I'll be able to also fix #2 by publishing this on npm as `@mozilla/properties-to-ftl`; the docs here have already been updated to match that. This effectively required switching the `resolve-chrome-uri` dependency to use a git submodule, as that package is not really suitable for wider publication (it's _really_ hacky).

### CODE REVIEW

File: lib/util-fail.js [hunk 1]
```diff
@@ -0,0 +1,21 @@
+import chalk from 'chalk'
+
+/**
+ * Log an error message and exit the process.
+ *
+ * @param {string | Error} error
+ * @returns {never}
+ */
+export function fail(error) {
```
Comment (gregtatum) [inline lib/util-fail.js:9]: praise: 👍

File: cli.js [hunk 2]
```diff
@@ -31,7 +31,7 @@ yargs(process.argv.slice(2))
     format: {
       alias: 'f',
       desc: "Command for Python code formatter. Set to '' to disable.",
-      default: 'python -m black',
+      default: './mach lint --fix',
```
Comment (gregtatum) [inline cli.js]: question: What happens if the user's path is wrong here and there is not `mach` file?

File: lib/update-localization-files.js [hunk 3]
```diff
@@ -62,19 +61,61 @@ export async function updateLocalizationFiles(propData, options) {
...
+        if (error.code === 'ENOENT') {
+          fail(`
+Python script formatter ${JSON.stringify(format)} not found.
+
+Use the --format option to customize, for example with "python -m black".
+Note that this may require installation with:
+
+  pip install black
+
+To disable Python formatting, use --format ''
```
Comment (gregtatum) [inline lib/update-localization-files.js:79]: Praise: Thanks for including the work-around.

File: lib/transform-properties.js [hunk 4]
```diff
@@ -21,8 +21,8 @@ export async function transformProperties(path, options = {}) {
     fail(`
 No migrations defined!
 
-In order to migrate strings to Fluent, the .properties file must include
-FTL metadata comments:
+In order to migrate strings to Fluent, the --ftl-path option must be set or
```
Comment (gregtatum) [inline lib/transform-properties.js:24]: praise: 👍

File: .gitmodules [hunk 5]
```diff
@@ -0,0 +1,4 @@
+[submodule "resolve-chrome-uri"]
```
Comment (gregtatum) [inline .gitmodules:1]: suggestion: This might need documenting (if it's not already) to properly pull in submodules. I know I have hit this stumbling block on onboarding with other projects.

**Review by gregtatum — APPROVED** [review]
Thanks for the updates!

File: cli.js (hunk 2 above)
Comment (eemeli) [reply cli.js]: As you found in the next comment, they should get an appropriate error. Commands that start with `.` are sought not just in the current working dir, but also in the repo root, so it should be pretty robust.

File: .gitmodules (hunk 5 above)
Comment (eemeli) [reply .gitmodules:1]: Good point. I'll add a mention to the README.
